on:
  workflow_dispatch:
    inputs:
      downloadURL:
        description: PaperMC download URL
        required: true
        type: string
      tags:
        description: docker/metadata-action tags definition
        required: true
        type: string

name: Build and push Docker image

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker-image:
    runs-on: ubuntu-latest
    name: Build and push Docker image
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: cronick/paper
          tags: ${{ inputs.tags }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.agent
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            DOWNLOAD_URL=${{ inputs.downloadURL }}
      
      - name: Summary
        run: |
          echo "## Image tags" >> $GITHUB_STEP_SUMMARY
          while IFS= read -r line ;
            do echo "- $line" >> $GITHUB_STEP_SUMMARY;
          done <<< "$tags"
        env:
          tags: ${{ steps.docker_meta.outputs.tags }}